eureka:
    client:
        service-url:
            defaultZone: http://127.0.0.1:10086/eureka
server:
    port: 10010
spring:
  application:
        name: gateway-service
  cloud:
    gateway:
      #全局过滤器
      default-filters:
        - AddResponseHeader= i-love,heima
      routes:
        #当前路由唯一标识
        - id: user-service-route
          #转发到服务的地址
#          uri: http://127.0.0.1:9091
          uri: lb://user-service
          #断言，当前路由转发规则（拦截规则）
          predicates:
#            - Path=/user/**
            - Path=/**
          #局部过滤器
          filters:
            #添加前辍
            - PrefixPath=/user
            #去除前辍
#            - StripPrefix=1