
server.port: 12000
#当前应用名称

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/feifeiwuxian/wf_springcloud_config.git
          username: feifeiwuxian
          password: wf186231
  rabbitmq:
    host: 49.234.8.74
    port: 5672
    username: guest
    password: guest
#注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
# 触发配置文件广播的地址actuator的endpoint
management.endpoints.web.exposure.include: bus-refresh